spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://192.168.10.11:3306/seckill

mybatis:
  configuration:
    #insert是否返回自增主键
    #在mapper.xml里insert的keyProperty指定主键字段
    use-generated-keys: true
    #是否匹配重命名列名
    use-column-label: true
    #是否启用驼峰命名转换
    map-underscore-to-camel-case: true
    #association和collection级联 延迟加载
    lazy-loading-enabled: true
    #association和collection级联级联 延迟加载 使用时才去查数据库
    aggressive-lazy-loading: false
    #开启二级缓存
    cache-enabled: true
  #Model类所在的包名,mapper.xml中的resultType可以直接写类名，不区分大小写
  type-aliases-package: com.lvlivejp.mybatisdemo.model
  #xml文件所在的目录
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.lvlivejp.mybatisdemo.mapper: debug

pagehelper:
  helperDialect: mysql
  reasonable: true
  #是否支持startPage(Object pamas)自定义参数名
  supportMethodsArguments: true
  #设置pamas中count的Key为countSql，执行过程中，如果pamas中有key为countSql的值，则取对应的值，否则就为null
  #count为boolean，所以countSql对应的值为true或false，true表示执行count的Sql，false反之
  params: count=countSql
  #CountSql的后缀，默认为selectId+"_COUNT"，可自定义，如果没找到自定义SQL，则还是执行默认的selectId+"_COUNT"语句
  #默认的countSql为替换select字段为count(0)
  countSuffix: _COUNT

mapper:
  mappers:
  - tk.mybatis.mapper.common.Mapper
  notEmpty: true
